%YAML 1.2
---
root: true
env:
  browser: true
  node: true
  commonjs: true
  es2022: true
  jest: true
extends:
  - eslint:recommended
plugins:
  - custom
parserOptions:
  ecmaVersion: latest
rules:
  strict:
    - error
    - global
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - always
  eol-last:
    - error
    - always
  no-var: error
  one-var:
    - error
    - let: consecutive
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  comma-spacing:
    - error
    - before: false
      after: true
  multiline-comment-style:
    - error
    - starred-block
  camelcase:
    - error
    - properties: never
  comma-dangle:
    - error
    - never
  eqeqeq:
    - error
    - always
  no-multi-spaces: error
  no-trailing-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 0
  object-curly-newline:
    - error
    - ObjectPattern:
        minProperties: 1
  prefer-object-has-own: error
  no-console: error
  no-unused-vars:
    - error
    - args: all
      argsIgnorePattern: ^_
  prefer-const: error
  no-multi-str: error
  no-lonely-if: error
  no-inline-comments: error
  no-extra-semi: error
  no-alert: error
  dot-notation: error
  object-shorthand:
    - error
    - properties
  custom/name-length:
    - error
    - 30

